name: Test
on:
  workflow_dispatch
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          echo "something" >> README.md
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add README.md
          git commit -m "Switch docs version back"
          git push
