name: Test
on:
  push:
    branches: main
    paths: trigger
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git checkout -b switch-docs-version
          echo "something" >> README.md
          git add README.md
          git commit -m "Switch docs version back"
          git push -u origin switch-docs-version
          gh pr create --fill --head switch-docs-version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
