name: Test
on:
  push:
    branches: main
    paths: trigger
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout -b switch-docs-version
          echo "something" >> README.md
          git add README.md
          git commit -m "Switch docs version back"
          git push -u origin switch-docs-version
          gh pr create --title "Switch docs version back" --body "" --head main -H switch-docs-version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
